apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: flash-tickets
type: Opaque
stringData:
  DATABASE_URL: "postgres://flash_tickets_app:flash_tickets_app@211.46.52.152:15432/flash_tickets"
  RABBITMQ_HOST: "b-45e98261-9f7f-45e7-a70f-7b9c33e154bc.mq.ap-northeast-2.on.aws"
  RABBITMQ_PORT: "5671"
  RABBITMQ_USER: "rmquser"
  RABBITMQ_PASSWORD: "guestguestguest"
  RABBITMQ_VHOST: /
  JWT_ACCESS_SECRET: "replace-with-access-Secret"
  JWT_REFRESH_SECRET: "change-me-refresh-dev"
  ADMIN_REGISTER_SECRET: "change-me-admin-dev"


