apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: flash-ticket
data:
  NODE_ENV: ""
  LOAD_ENV_FILES: ""
  PORT: ""
  PAYMENT_REQUEST_QUEUE: ""
  PAYMENT_RESULT_QUEUE: ""
  REDIS_HOST: ""
  REDIS_PORT: ""
  REDIS_TLS: ""
  DATABASE_SSL_MODE: ""
  JWT_ACCESS_EXP: ""
  JWT_REFRESH_EXP: ""
  QUEUE_READY_CAPACITY: ""
  QUEUE_GATE_TOKEN_TTL_MS: ""
  QUEUE_PROMOTION_INTERVAL_MS: ""
  QUEUE_WS_REFRESH_MS: ""
  CLIENT_URL: ""
