apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: flash-ticket
type: Opaque
stringData:
  DATABASE_URL: ""
  RABBITMQ_URL: ""
  JWT_ACCESS_SECRET: ""
  JWT_REFRESH_SECRET: ""
  ADMIN_REGISTER_SECRET: ""
