apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: flash-ticket
data:
  NODE_ENV: "production"
  LOAD_ENV_FILES: "false"
  PORT: "3000"
  QUEUE_GATEWAY_PORT: "3000"
  JWT_ACCESS_EXP: "20m"
  JWT_REFRESH_EXP: "7d"
  REDIS_HOST: "master.flash-tickets-redis.rrzszk.apn2.cache.amazonaws.com"
  REDIS_PORT: "6379"
  REDIS_TLS: "true"
  QUEUE_READY_CAPACITY: "400"
  QUEUE_GATE_TOKEN_TTL_MS: "1200000"
  QUEUE_PROMOTION_INTERVAL_MS: "3000"
  QUEUE_WS_REFRESH_MS: "4000"
  DATABASE_SSL_MODE: "disable"
