apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: flash-ticket
type: Opaque
stringData:
  DATABASE_URL: "postgres://flash_tickets_app:flash_tickets_app@211.46.52.152:15432/flash_tickets"
  JWT_ACCESS_SECRET: "replace-with-access-Secret"
  JWT_REFRESH_SECRET: "change-me-refresh-dev"
  ADMIN_REGISTER_SECRET: "change-me-admin-dev"
