apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: flash-ticket
type: Opaque
stringData:
  DATABASE_URL: ""
  JWT_ACCESS_SECRET: ""
  JWT_REFRESH_SECRET: ""
  ADMIN_REGISTER_SECRET: ""
