apiVersion: v1
kind: Secret
metadata:
  name: pay-secret
  namespace: flash-ticket
type: Opaque
stringData:
  RABBITMQ_URL: "amqps://rmquser:guestguestguest@b-45e98261-9f7f-45e7-a70f-7b9c33e154bc.mq.ap-northeast-2.on.aws:5671/%2f"
