apiVersion: v1
kind: ConfigMap
metadata:
  name: pay-config
  namespace: flash-ticket
data:
  NODE_ENV: ""
  LOAD_ENV_FILES: ""
  PAY_HEALTH_PORT: ""
  PAYMENT_REQUEST_QUEUE: ""
  PAYMENT_RESULT_QUEUE: ""
  PAYMENT_SUCCESS_RATE: ""
  PAYMENT_PROCESSING_MIN_MS: ""
  PAYMENT_PROCESSING_MAX_MS: ""
