apiVersion: v1
kind: Secret
metadata:
  name: pay-secret
  namespace: flash-tickets
type: Opaque
stringData:
  RABBITMQ_HOST: "b-45e98261-9f7f-45e7-a70f-7b9c33e154bc.mq.ap-northeast-2.on.aws"
  RABBITMQ_PORT: "5671"
  RABBITMQ_USER: "rmquser"
  RABBITMQ_PASSWORD: "guestguestguest"
