apiVersion: apps/v1
kind: Deployment
metadata:
  name: flash-gateway
  namespace: flash-ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flash-gateway
  template:
    metadata:
      labels:
        app: flash-gateway
    spec:
      containers:
        - name: gateway
          image: 339712948064.dkr.ecr.ap-northeast-2.amazonaws.com/flash-tickets/gateway:amd64
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: gateway-secret
            - configMapRef:
                name: gateway-config
          readinessProbe:
            httpGet:
              path: /queue/healthz
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /queue/healthz
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: flash-gateway
  namespace: flash-ticket
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /queue/healthz
spec:
  selector:
    app: flash-gateway
  ports:
    - name: http
      port: 3000
      targetPort: 3000
