apiVersion: apps/v1
kind: Deployment
metadata:
  name: flash-pay
  namespace: flash-ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flash-pay
  template:
    metadata:
      labels:
        app: flash-pay
    spec:
      # 고가용성을 위한 Pod 분산 설정
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - flash-pay
              topologyKey: topology.kubernetes.io/zone
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - flash-pay
              topologyKey: kubernetes.io/hostname
      containers:
        - name: pay
          image: 339712948064.dkr.ecr.ap-northeast-2.amazonaws.com/flash-tickets/pay:amd64
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          envFrom:
            - secretRef:
                name: pay-secret
            - configMapRef:
                name: pay-config
