apiVersion: apps/v1
kind: Deployment
metadata:
  name: flash-web
  namespace: flash-ticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flash-web
  template:
    metadata:
      labels:
        app: flash-web
    spec:
      containers:
        - name: web
          image: 339712948064.dkr.ecr.ap-northeast-2.amazonaws.com/flash-tickets/web:amd64
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: web-config
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: flash-web
  namespace: flash-ticket
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  selector:
    app: flash-web
  ports:
    - name: http
      port: 80
      targetPort: 80
