apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flash-ingress
  namespace: flash-tickets
  annotations:
    spec.ingressClassName: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:ap-northeast-2:339712948064:certificate/00596951-525b-4bdd-8451-a7a1081fa19b,arn:aws:acm:ap-northeast-2:339712948064:certificate/8f0b62ea-3544-48c2-824d-bea976bb49af'
    alb.ingress.kubernetes.io/subnets: subnet-025f2ee8789712d88,subnet-041b5e3307bdb4253
spec:
  rules:
    - host: api.highgarden.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flash-api
                port:
                  number: 4000
    - host: gateway.highgarden.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flash-gateway
                port:
                  number: 3000
    - host: www.highgarden.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flash-web
                port:
                  number: 80
