apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Database
  DATABASE_URL: "postgres://flash_tickets_app:flash_tickets_app@211.46.52.152:15432/flash_tickets"

  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""

  # RabbitMQ
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  PAYMENT_REQUEST_QUEUE: "payments_request"
  PAYMENT_RESULT_QUEUE: "payments_result"

  # JWT
  JWT_ACCESS_EXP: "15m"
  JWT_REFRESH_EXP: "7d"

  # Queue Settings
  QUEUE_READY_CAPACITY: "50"
  QUEUE_GATE_TOKEN_TTL_MS: "120000"
  QUEUE_PROMOTION_INTERVAL_MS: "500"
  QUEUE_WS_REFRESH_MS: "3000"

  # Application
  CLIENT_URL: "http://localhost:5173"
  NODE_ENV: "production"
