apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../eks/deployments/api-deployment.yaml

images:
- name: 339712948064.dkr.ecr.ap-northeast-2.amazonaws.com/flash-tickets/api
  newName: 339712948064.dkr.ecr.ap-northeast-2.amazonaws.com/flash-tickets/api
  newTag: 04a8a4aaee01888fa4f6aed397e1bb9c2529f402
