apiVersion: v1
kind: Service
metadata:
  name: flash-api
  namespace: flash-ticket
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  selector:
    app: flash-api
  ports:
    - name: http
      port: 4000
      targetPort: 4000
