apiVersion: apps/v1
kind: Deployment
metadata:
  name: flash-gateway
  namespace: flash-ticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flash-gateway
  template:
    metadata:
      labels:
        app: flash-gateway
    spec:
      containers:
        - name: gateway
          image: 339712948064.dkr.ecr.ap-northeast-2.amazonaws.com/flash-tickets/gateway:amd64-20251028-ha-live
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: gateway-secret
            - configMapRef:
                name: gateway-config
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /queue/healthz
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /queue/healthz
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
