apiVersion: v1
kind: Service
metadata:
  name: flash-gateway
  namespace: flash-ticket
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /queue/healthz
spec:
  selector:
    app: flash-gateway
  ports:
    - name: http
      port: 3000
      targetPort: 3000
